### ISSUE TITLE
Publish to NPM

### ISSUE THREAD

**Issue by fczbkk** [rpl/grunt-jpm#1]
Can you please [publish this package to NPM](https://docs.npmjs.com/cli/publish), so that it is easier to use?

It is possible to add it via [tarball path](https://github.com/rpl/grunt-jpm/archive/0.1.0.tar.gz). But it would be great if I could just `npm install` it. Also, it would make updating to newer version much easier.

Thanks.

**Comment by rpl** [comment]
@fczbkk absolutely, just done: https://www.npmjs.com/package/grunt-jpm

PS: the jpm repo is very active (jpm already moved from the version 0.0.16 used by this package to the recent v0.0.23), so this package needs to be updated as well (I'm going to do it asap)  
PPS: it is possible to install directly from a github repo as well using "npm install rpl/grunt-jpm --save"
